project_id = "eszaapcfhuawjoobtbrp"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.send-invitation-email]
verify_jwt = false

[functions.accept-invitation]
verify_jwt = false

[functions.get-invitation]
verify_jwt = false

[functions.register-invited-user]
verify_jwt = false