
project_id = "none"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Disable Edge Functions dev detection
[functions]
[functions.accept-invitation]
verify_jwt = false
