// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tistxxdthzlpldrdipzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpc3R4eGR0aHpscGxkcmRpcHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1MjI5MjAsImV4cCI6MjA1OTA5ODkyMH0.vPeAkzdu8457e-5pzfeikKxYhF3yqLyyWX46NTd1rwM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);